# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 200c58e26827a479c14979b58fc89a3109aabd9ce7cb76bb039f9b46f2f2d66f0757877e37513af1d3f6eb2b067e4d4037b4b1eabf57b5734bacec3cc27be74b

test:
  secret_key_base: 7aca22eeba662eb53c638b7b9ec09914d8fbff574d18901da04de111fa4245c416a4baf362cfdf60c30e599d8961af9c8c1f961e281b4f9297dd6283c7c4c62c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
